"""Forwards requests to the real wiby.net servers and archives the responses.

This is the preservation-critical path. While the official backend is still
answering, every request/response pair is written to disk as a fixture. Those
fixtures are ground truth: they let the offline backend replay real server
behavior instead of relying on schemas reconstructed from the binary.

Fixtures are keyed by endpoint so that later captures of the same endpoint
accumulate rather than overwrite -- different game states produce different
responses, and we want all of them.
"""
from __future__ import annotations

import gzip
import hashlib
import http.client
import json
import ssl
import threading
import zlib
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

from .assets import AssetArchiver
from .redact import scrub, scrub_headers

# Headers that describe the hop, not the message; regenerated by the forwarder.
_HOP_BY_HOP = {
    "connection",
    "keep-alive",
    "proxy-authenticate",
    "proxy-authorization",
    "te",
    "trailers",
    "transfer-encoding",
    "upgrade",
    "content-length",
    "host",
    "accept-encoding",
}


class UpstreamError(RuntimeError):
    pass


class Forwarder:
    """Performs the real request and archives the exchange."""

    def __init__(
        self,
        fixture_dir: Path,
        timeout: float = 30.0,
        archiver: "AssetArchiver | None" = None,
    ):
        self.dir = fixture_dir
        self.dir.mkdir(parents=True, exist_ok=True)
        self.timeout = timeout
        self.archiver = archiver
        self._lock = threading.Lock()
        self._ctx = ssl.create_default_context()

    def fetch(
        self,
        *,
        method: str,
        url: str,
        headers: dict[str, str],
        body: bytes,
    ) -> tuple[int, dict[str, str], bytes]:
        parsed = urlparse(url)
        host = parsed.hostname or ""
        port = parsed.port or (443 if parsed.scheme == "https" else 80)
        path = parsed.path or "/"
        if parsed.query:
            path += "?" + parsed.query

        if parsed.scheme == "https":
            conn: http.client.HTTPConnection = http.client.HTTPSConnection(
                host, port, timeout=self.timeout, context=self._ctx
            )
        else:
            conn = http.client.HTTPConnection(host, port, timeout=self.timeout)

        send_headers = {
            k: v for k, v in headers.items() if k.lower() not in _HOP_BY_HOP
        }
        send_headers["Host"] = host
        # Ask for identity so archived bodies are readable; the game's own
        # gzip preference is restored on the way back out.
        send_headers["Accept-Encoding"] = "identity"

        try:
            conn.request(method, path, body=body or None, headers=send_headers)
            resp = conn.getresponse()
            raw = resp.read()
            status = resp.status
            resp_headers = {k: v for k, v in resp.getheaders()}
        except (OSError, http.client.HTTPException) as exc:
            raise UpstreamError(f"{method} {url}: {exc}") from exc
        finally:
            try:
                conn.close()
            except OSError:
                pass

        decoded = _decompress(raw, resp_headers.get("Content-Encoding", ""))

        # Pull the layout and phantom blobs before the CDN disappears. The
        # game fetches these directly, so this is our only chance to see them.
        # NB: do not name this `body` -- that is the *request* body parameter,
        # and shadowing it corrupts the archive record.
        if self.archiver is not None:
            response_json = _as_json(decoded)
            if response_json is not None:
                added = self.archiver.harvest(response_json)
                if added:
                    print(f"[assets] queued {added} blob(s) from {urlparse(url).path}")

        self._archive(
            method=method,
            url=url,
            req_headers=headers,
            req_body=body,
            status=status,
            resp_headers=resp_headers,
            resp_body=decoded,
        )
        return status, resp_headers, decoded

    # ---------------------------------------------------------- archive

    def _archive(
        self,
        *,
        method: str,
        url: str,
        req_headers: dict[str, str],
        req_body: bytes,
        status: int,
        resp_headers: dict[str, str],
        resp_body: bytes,
    ) -> None:
        endpoint = (urlparse(url).path or "/").strip("/").replace("/", "_") or "root"
        # Distinguish different request shapes hitting the same endpoint.
        # Archiving must never be the thing that breaks a response, so tolerate
        # an empty or unexpected body rather than raising mid-request.
        raw_request = req_body if isinstance(req_body, (bytes, bytearray)) else b""
        digest = hashlib.sha256(raw_request).hexdigest()[:12]
        out = self.dir / f"{endpoint}.jsonl"

        entry: dict[str, Any] = {
            "ts": datetime.now(timezone.utc).isoformat(),
            "method": method,
            "url": url,
            "status": status,
            "request_digest": digest,
            "request_headers": scrub_headers(req_headers),
            "request_body": scrub(_as_json(raw_request)),
            "response_headers": dict(resp_headers),
            "response_body": scrub(_as_json(resp_body)),
        }
        with self._lock:
            with out.open("a", encoding="utf-8") as fh:
                fh.write(json.dumps(entry, ensure_ascii=False) + "\n")


def _decompress(data: bytes, encoding: str) -> bytes:
    enc = (encoding or "").lower()
    try:
        if "gzip" in enc:
            return gzip.decompress(data)
        if "deflate" in enc:
            return zlib.decompress(data)
    except (OSError, EOFError, zlib.error):
        pass
    return data


def _as_json(body: bytes) -> Any:
    if not body:
        return None
    try:
        text = body.decode("utf-8")
    except UnicodeDecodeError:
        return {"__binary__": body.hex()[:8192], "__len__": len(body)}
    try:
        return json.loads(text)
    except ValueError:
        return text


